version: '3.8'

services:
  todo-app:
    build: .
    ports:
      - "9092:9092"
    environment:
      - TODO_PORT=9092
      - TODO_PASSWORD=secret123
    volumes:
      - todo-data:/data
    restart: unless-stopped

volumes:
  todo-data:
